services:
  booking-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: booking-node
    ports:
      - 80:8080

  database-mongo:
    image: mongo
    container_name: database-mongo
    volumes:
      - ./db-booking-hotel:/data/db
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: booking-react
    ports: 3000:3000
